add docs for depends_on; tweak instance_id for components
architect-team/architect-cli pull request #384
Opened 2021-04-27 20:13 UTC by dan-barrett

@tjhiggins note: I tweaked the instance_id. I didn't realize this gets used for the component graph too, not just on local deployments. I don't think it matters but I figured `*-component` makes more sense than `*-local`

2021-04-27 20:35 UTC, tjhiggins requested changes

2021-04-27 20:35 UTC, tjhiggins commented on src/dependency-manager/src/manager.ts
> +      node.instance_id = `${Refs.safeRef(component.getRef())}-component`;
Missed this in the initial review. Remove setting node.instance_id here. Set in the local-manager getGraph method when we loop over the nodes for a component. 

https://github.com/architect-team/architect-cli/blob/master/src/common/dependency-manager/local-manager.ts#L45

2021-04-27 20:43 UTC, dan-barrett commented
@tjhiggins updated

2021-04-28 17:51 UTC, dan-barrett commented
@tjhiggins just a reminder on this

2021-04-28 18:02 UTC, merged