Use buildpack img
architect-team/architect-cli pull request #802
Opened 2023-01-20 16:28 UTC by mtgoncalves1

## Overview
Allow application build with a buildpack builder.

## Changes
Add a `buildpack` field to the build block. When `Dockerfile` is not found or not specified, the buildpack builder will be triggered and build an image of the service.

## Docs
https://github.com/architect-team/architect-documentation/pull/35

## Pictures
Set `buildpack` to true in the build block.
```
build:
      context: ./go/server
      buildpack: true
```

#### Flask starter project
Updated command to   
```
command: gunicorn -w ${{ secrets.gunicorn_workers }} -b 0.0.0.0:${{ services.flask.interfaces.main.port }} "flaskr:create_app()"
```
and add an environment variable
```
FLASK_APP: flaskr
```
% architect dev  
![Screenshot 2023-01-20 at 10 17 52 AM](https://user-images.githubusercontent.com/102971990/213734038-f412e9af-d0cc-4ae1-9d26-985594230c71.png)  
   
% architect dev --debug=false  
It was built but did not start.

#### NodeJS starter project
% architect dev    
<img width="955" alt="Screenshot 2023-01-20 at 12 42 47 PM" src="https://user-images.githubusercontent.com/102971990/213768488-4ceb34ce-8ac0-4f73-b7b4-3f4651d7e964.png">
 
% architect dev --debug=false   
<img width="955" alt="Screenshot 2023-01-20 at 12 42 47 PM" src="https://user-images.githubusercontent.com/102971990/213768488-4ceb34ce-8ac0-4f73-b7b4-3f4651d7e964.png">

% architect-dev register   
% architect-dev deploy    
<img width="958" alt="Screenshot 2023-01-20 at 12 47 16 PM" src="https://user-images.githubusercontent.com/102971990/213770974-a6e80824-e681-4e88-8bd6-3d1357c76e60.png">

#### Spring boot starter project  
- Commented out `<packaging>war</packaging>`. It built fine with this but will fail to run because you need to provide a start command.
- Added a `system.properties` file at the root directory
```
java.runtime.version=18.0.2.1
maven.version=3.6.2
```

% architect dev   
![Screenshot 2023-01-20 at 10 50 04 AM](https://user-images.githubusercontent.com/102971990/213743359-0a679fef-fc5f-4ce8-8264-77b0e52205f9.png)
  
% architect dev --debug=false
<img width="837" alt="Screenshot 2023-01-20 at 12 19 15 PM" src="https://user-images.githubusercontent.com/102971990/213763249-22a5a9d8-a89f-48af-a735-7cb8bac91b6b.png">

  
% architect-dev register   
% architect-dev deploy    
![Screenshot 2023-01-20 at 10 57 42 AM](https://user-images.githubusercontent.com/102971990/213745164-8e1e6b43-4af8-4e47-96d1-1f4d4226d5c3.png)

2023-01-20 18:00 UTC, mueschm requested changes
Besides the comments here I have a chat thread going in our engineering slack about how we should handle the schema verification change.

2023-01-20 19:54 UTC, mtgoncalves1 commented on src/commands/register.ts
> +    for (const cache_dir of seen_cache_dir) {
I just thought that if I put it there, I don't have to return `seen_cache_dir`.

2023-01-20 19:57 UTC, mtgoncalves1 commented on src/commands/register.ts
> -      try {
I believe we only remove compose file when the buildx failed to build.

2023-01-20 20:10 UTC, mueschm commented on src/commands/register.ts
> -      try {
Sorry left this comment in on accident. I realize this got moved but it should be moved back.

2023-01-20 20:12 UTC, mueschm commented on src/commands/register.ts
> +    for (const cache_dir of seen_cache_dir) {
But `DockerBuildXUtils.build` happens after this code runs. `setImageRef` is done on line 213 and the build is on line 240.

2023-01-20 20:15 UTC, mtgoncalves1 commented on src/commands/register.ts
> -      try {
Sorry. I moved it back so it can remove the compose file in the catch block.

2023-01-20 20:23 UTC, mtgoncalves1 commented on src/commands/register.ts
> +    for (const cache_dir of seen_cache_dir) {
I see. So, we only want to move the `cache_dir` if the build was successful. I'll make that change.

2023-01-20 20:37 UTC, mueschm commented on src/commands/register.ts
> +    for (const cache_dir of seen_cache_dir) {
Well the cache directory has the build artifacts we need to cache. This is mostly used for things like Github Actions.

2023-01-23 02:29 UTC, mueschm approved these changes
My testing is showing this working as expected. Given the nature of this I am going to ask 1 other engineer to sanity check as well before we merge. Otherwise looking good.

2023-01-23 14:11 UTC, mtgoncalves1 commented
> My testing is showing this working as expected. Given the nature of this I am going to ask 1 other engineer to sanity check as well before we merge. Otherwise looking good.

Thank you for the review and that sounds good.

2023-01-26 19:27 UTC, merged