Convert compose interpolations
architect-team/architect-cli pull request #881
Opened 2023-04-07 15:55 UTC by mtgoncalves1

## Overview
Closes https://gitlab.com/architect-io/architect-cli/-/issues/467.  
Make sure docker compose interpolation gets converted to our syntax correctly.

## Changes
- Convert any compose environment variables with the format of ${*} to Architect format ${{ * }} and create a secret for each of them

## Tests
docker-compose.yml
```
version: '3.2'
services:
  db:
    image: "postgres:${POSTGRES_VERSION}"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
```

Run the `init` command. It should result in the following architect file.   
$ architect-local init --from-compose=docker-compose.yml test
```
name: test
services:
  db:
    image: postgres:${{ secrets.POSTGRES_VERSION }}
    environment:
      POSTGRES_USER: ${{ secrets.DB_USER }}
      POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
      POSTGRES_DB: ${{ secrets.DB_NAME }}
    reserved_name: db
secrets:
  POSTGRES_VERSION:
    required: true
  DB_USER:
    required: true
  DB_PASSWORD:
    required: true
  DB_NAME:
    required: true
```

2023-04-10 13:43 UTC, mueschm commented
The `server_online.sh` script is not working. More than likely, the number of services changed due to the test update. Should be easy and a good learning experience to update the script and fix everything.

2023-04-10 14:09 UTC, tjhiggins commented
> The `server_online.sh` script is not working. More than likely, the number of services changed due to the test update. Should be easy and a good learning experience to update the script and fix everything.

I had the same issue. Which is how I went down the --wait path. This pr should fix the issue:
https://github.com/architect-team/architect-cli/pull/880

2023-04-12 14:14 UTC, mtgoncalves1 commented
>  I think that secrets specified as just `${VARIABLE}` or `$VARIABLE` shouldn't be required secrets.
Ok. I'll leave them as 
```
secrets:
  VARIABLE:
```

2023-04-12 14:49 UTC, ryan-cahill commented
> > I think that secrets specified as just `${VARIABLE}` or `$VARIABLE` shouldn't be required secrets.
> > Ok. I'll leave them as
> 
> ```
> secrets:
>   VARIABLE:
>     default:
> ```

I think that rather than an empty default property, `required: false` might be more appropriate

2023-04-14 14:59 UTC, ryan-cahill requested changes

2023-04-14 14:59 UTC, ryan-cahill commented on src/common/docker-compose/converter.ts
> +  private static parseSecrets(pattern: RegExp, str: string, use_default: boolean, required: boolean): { service_spec: Dictionary<ServiceSpec>, secrets: Dictionary<SecretDefinitionSpec> } {
`str` should be a little more specific about what it is

2023-04-18 14:12 UTC, ryan-cahill approved these changes

2023-04-18 14:15 UTC, merged